- name: Editing chrony.conf file
  copy:
    src: chrony.conf
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 644

  notify: Restarting chrony

- name: Adding service in firewall
  ansible.posix.firewalld:
    service: ntp
    permanent: yes
    state: enabled

  notify: Reloading firewall
